name: types
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Set up Yarn cache
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: yarn
      - run: yarn install --frozen-lockfile
      - run: yarn check:types
concurrency:
  group: check-types
  cancel-in-progress: true
on: push
